# Site settings
title: 琉璃康康
SEOTitle: 琉璃康康 | HK Blog
header-img: "img/home.jpg"
tagline: "cn"  
description: "琉璃苣的花语是勇气 | 琉璃康康"  
keyword: "琉璃康康, 康民仆, HK, HK Blog, 博客, 个人网站, 通信, Linux, 摄影"
baseurl: ""
url: "http://www.hk314.me"

# About/contact
owner: 
  name: " HK"
  email: kangminpu@126.com
  bio: "琉璃康康"

# Data
#gavatar: http://dreamofbook.qiniudn.com/Az..png
favicon: img/favicon_new.png

# SNS settings
RSS: false
github_username: MinpuKang
weibo_username: kangminpu
zhihu_username: liulikangkang
loft_username: liulikangkang
tuchong_username: liulikangkang

# Build settings  
# use Github Flavored Markdown !important  
# document: http://jekyllrb.com/docs/configuration/#kramdown  
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 8
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: Asia/Shanghai

# Defaults for posts
defaults:
  -
    scope: 
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "琉璃康康"
      header-img: "img/post.jpg" # We don't want posts without a header image, that whould mean white on white

# Comments 
comments :
  provider : duoshuo
  duoshuo :
    short_name : hk
  disqus :
      short_name : hk

# Analytics and webmaster tools stuff goes here
google_analytics: 
google_verify:



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "如猛虎细嗅蔷薇，<br>做一些自己喜欢的事情！"
sidebar-avatar: img/avatar-hk.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`


# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value



# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:


# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true


# Friends
friends: [
    {
    #     title: "Su",
    #     href: "http://su.gallery/"
    # },{
        title: "iDom",
        href: "http://idom.me/"
    }
]

# Links to include in footer navigation
